# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true

# Mod properties
name=${rootProject.name}
group=com.anthonyhilyard.${name.toLowerCase()}
author=anthonyhilyard
modVersion=1.6.8
enabledPlatforms=fabric,forge,neoforge
fabric.loom.disableRemappedVariants=true

# Minecraft properties
minecraftVersion=1.21.1

# Dependencies
fabricLoaderVersion=0.16.9
fabricVersion=0.108.0+1.21.1
forgeVersion=1.21.1-52.0.28
neoforgeVersion=21.1.77
