modLoader="javafml"
loaderVersion="[48,)"
license="CC BY-NC-ND 4.0"

[[mods]]
modId="advancementplaques"
version="${file.jarVersion}"
displayName="Advancement Plaques"
displayURL="https://anthonyhilyard.com/"
updateJSONURL="https://mc-update-check.anthonyhilyard.com/499826"
logoFile="icon.png"
authors="Grend"
description="Replaces standard advancement toasts with fancy plaques."

[[dependencies.advancementplaques]]
	modId="forge"
	mandatory=true
	versionRange="[48,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.advancementplaques]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.20.2,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.advancementplaques]]
	modId="iceberg"
	mandatory=true
	versionRange="[1.1.16,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.advancementplaques]]
	modId="toastcontrol"
	mandatory=false
	versionRange="[8.5,)"
	ordering="NONE"
	side="BOTH"