modLoader="javafml"
loaderVersion="[38,)"
license="MIT"

[[mods]]
modId="advancementplaques"
version="${file.jarVersion}"
displayName="Advancement Plaques"
displayURL="https://anthonyhilyard.com/"
updateJSONURL="https://mc-curse-update-checker.herokuapp.com/499826"
logoFile="icon.png"
authors="Grend"
description="Replaces standard advancement toasts with fancy plaques."

[[dependencies.advancementplaques]]
	modId="forge"
	mandatory=true
	versionRange="[38,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.advancementplaques]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.18]"
	ordering="NONE"
	side="BOTH"

[[dependencies.advancementplaques]]
	modId="iceberg"
	mandatory=true
	versionRange="[1.0.29,)"
	ordering="NONE"
	side="BOTH"
