architectury {
	common {
		clear()
		add(rootProject.enabledPlatforms.split(','))
	}
}

loom {
	accessWidenerPath = file("src/main/resources/advancementplaques.accesswidener")
}

repositories {
	maven {
		name = "WTHIT"
		url = "https://maven.bai.lol"
	}
}

dependencies {
	// We depend on Fabric Loader here to use the Fabric @Environment annotations,
	// which get remapped to the correct annotations on each platform.
	// Do NOT use other classes from Fabric Loader.
	implementation "net.fabricmc:fabric-loader:$rootProject.fabricLoaderVersion"

	implementation fileTree(dir: "../libs", include: ["*.jar"])

	compileOnly "curse.maven:jade-324717:8285136"
	// 26.2 version of WTHIT is not yet available.
	compileOnly "curse.maven:wthit-440979:7880671"
}
