modLoader="javafml"
loaderVersion="[1,)"
license="CC BY-NC-ND 4.0"

[[mods]]
modId="advancementplaques"
version="${version}"
displayName="Advancement Plaques"
displayURL="https://anthonyhilyard.com/"
updateJSONURL="https://mc-update-check.anthonyhilyard.com/499826"
logoFile="icon.png"
authors="Grend, Mat0u5"
description="Replaces standard advancement toasts with fancy plaques."

[[dependencies.advancementplaques]]
	modId="neoforge"
	type="required"
	versionRange="[26.2,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.advancementplaques]]
	modId="minecraft"
	type="required"
	versionRange="[26.2,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.advancementplaques]]
	modId="iceberg"
	type="required"
	versionRange="[1.4.2,)"
	ordering="AFTER"
	side="BOTH"

[[dependencies.advancementplaques]]
	modId="prism"
	type="optional"
	versionRange="[1.1.2,)"
	ordering="AFTER"
	side="BOTH"

[[dependencies.advancementplaques]]
	modId="toastcontrol"
	type="optional"
	versionRange="[9.0,)"
	ordering="AFTER"
	side="BOTH"